In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Advertising.csv")

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X = df.drop("sales", axis = 1)

In [5]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [6]:
y = df["sales"]

In [7]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [8]:
from sklearn.preprocessing import PolynomialFeatures

In [10]:
polynomial_converter = PolynomialFeatures(include_bias=False)

In [11]:
poly_features = polynomial_converter.fit_transform(X)

In [13]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

#### Applying linear regression model

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=42)

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
#Creating instance of the polynomial linear regression model
poly_model = LinearRegression()

In [18]:
#Fitting the model - Learn from the data
poly_model.fit(X_train,y_train)

LinearRegression()

In [19]:
predicted_values = poly_model.predict(X_test)

In [20]:
predicted_values

array([17.22263805, 22.76431942, 20.34240311,  7.63823081, 24.43070212,
       12.62670906, 22.77581025,  8.17257308, 12.1434595 , 15.59295774,
        7.70321153,  8.13970713, 11.94050296,  6.00239435, 10.52156294,
       12.29998882,  6.73498649, 16.59405075, 10.56966577, 19.02896977,
       20.15426466, 13.93688799,  9.49270709, 22.09007022,  8.81726594,
        7.63831359, 22.36845761, 12.63105172, 10.12142254,  6.02913868,
       11.66988463, 10.06960308, 23.4843312 ,  9.85934368, 15.33869793,
       21.07332794, 10.9676273 , 20.14554654, 11.74470764,  6.4231513 ,
       10.71450186, 12.83429003,  9.18959984,  8.91317752, 11.87160951,
        6.97626924,  9.95713385, 14.69620775, 10.1058211 , 11.2550714 ,
       14.04197399, 12.14298425,  8.96411937,  7.54429236,  8.39739662,
       10.86854626,  9.89471268, 25.23373739,  6.79877024, 11.96203194])

In [21]:
poly_model.coef_

array([ 0.05478172,  0.01311214,  0.01086391, -0.00011074,  0.00108048,
       -0.00010764,  0.00030191,  0.00017541,  0.00010075])

In [29]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

In [28]:
230.1 ** 2

52946.009999999995

### Performance evaluation of polynomial regression model

In [30]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [31]:
MAE = mean_absolute_error(y_test, predicted_values)

In [32]:
MSE = mean_squared_error(y_test, predicted_values)

In [33]:
RMSE = np.sqrt(MSE)

In [37]:
print ("MAE:",MAE)
print ("MSE:",MSE)
print ("RMSE:",RMSE)

MAE: 0.5905974833808035
MSE: 0.5231944949055423
RMSE: 0.7233218473857556


#### Performance metrics of earlier linear regression model
MAE: 1.5116692224549089 <br/>
MSE: 3.796797236715219  <br/>
RMSE: 1.9485372043446385 <br/>

#### What we can see is that our polynomial regression model has performed much better than linear regression model